//
// Created by Idir on 21/04/2023.
//

#ifndef VECTOR_IMAGE_EDITOR_STATES_H
#define VECTOR_IMAGE_EDITOR_STATES_H

typedef enum { MAIN_MENU, CHOOSE_SIZE, ON_CANVAS } STATE;

#endif //VECTOR_IMAGE_EDITOR_STATES_H
